<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relisEugene" nsURI="http://www.example.org/relisEugene" nsPrefix="relisEugene">
  <eClassifiers xsi:type="ecore:EClass" name="IndependentDynamicCategory" eSuperTypes="#//CategoryType"/>
  <eClassifiers xsi:type="ecore:EClass" name="String"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeExclude" eSuperTypes="#//ConflictDetection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Majority" eSuperTypes="#//ConflictResolution"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompareGraph" eSuperTypes="#//Synthesis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusion" eSuperTypes="#//Criteria"/>
  <eClassifiers xsi:type="ecore:EClass" name="Question" eSuperTypes="#//QA"/>
  <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorytype" lowerBound="1"
        eType="#//CategoryType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Answer" eSuperTypes="#//QA"/>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DependentDynamicCategory" eSuperTypes="#//CategoryType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Synthesis" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//CategoryType"/>
  <eClassifiers xsi:type="ecore:EClass" name="FreeCategory" eSuperTypes="#//CategoryType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="string" lowerBound="1"
        eType="#//String" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conflict" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflictdetection" eType="#//ConflictDetection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflictresolution" eType="#//ConflictResolution"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Veto" eSuperTypes="#//AssignmentMode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticCategory" eSuperTypes="#//CategoryType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field"/>
  <eClassifiers xsi:type="ecore:EClass" name="Phase" eSuperTypes="#//Screening">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="#//Field"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="QA" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multivalued" eSuperTypes="#//Category"/>
  <eClassifiers xsi:type="ecore:EClass" name="Screening" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" lowerBound="1"
        eType="#//Criteria" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" upperBound="-1"
        eType="#//Validation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleReviewers" eSuperTypes="#//Screening">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflict" lowerBound="1"
        eType="#//Conflict" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentmode" eType="#//AssignmentMode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictDetection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Criteria" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictResolution" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryCategory" eSuperTypes="#//Category"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusion" eSuperTypes="#//Criteria"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialValue" eSuperTypes="#//Category"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataExtraction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//Category"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentMode" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReLiS" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qa" eType="#//QA" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataextraction" eType="#//DataExtraction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screening" eType="#//Screening"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synthesis" eType="#//Synthesis"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
