/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import shapes.Circle;
import shapes.Rectangle;
import shapes.ShapeConstructor;
import shapes.ShapesPackage;
import shapes.Triangle;
import shapes.myconstructor.services.ShapesGrammarAccess;

@SuppressWarnings("all")
public class ShapesSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ShapesGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ShapesPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ShapesPackage.CIRCLE:
				sequence_Circle(context, (Circle) semanticObject); 
				return; 
			case ShapesPackage.RECTANGLE:
				sequence_Rectangle(context, (Rectangle) semanticObject); 
				return; 
			case ShapesPackage.SHAPE_CONSTRUCTOR:
				sequence_ShapeConstructor(context, (ShapeConstructor) semanticObject); 
				return; 
			case ShapesPackage.TRIANGLE:
				sequence_Triangle(context, (Triangle) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Shape returns Circle
	 *     Circle returns Circle
	 *
	 * Constraint:
	 *     (name=EString radius=EInt?)
	 * </pre>
	 */
	protected void sequence_Circle(ISerializationContext context, Circle semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Shape returns Rectangle
	 *     Rectangle returns Rectangle
	 *
	 * Constraint:
	 *     (name=EString length=EInt? width=EInt?)
	 * </pre>
	 */
	protected void sequence_Rectangle(ISerializationContext context, Rectangle semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ShapeConstructor returns ShapeConstructor
	 *
	 * Constraint:
	 *     (name=EString (shape+=Shape shape+=Shape*)?)
	 * </pre>
	 */
	protected void sequence_ShapeConstructor(ISerializationContext context, ShapeConstructor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Shape returns Triangle
	 *     Triangle returns Triangle
	 *
	 * Constraint:
	 *     (name=EString a=EInt? b=EInt? c=EInt?)
	 * </pre>
	 */
	protected void sequence_Triangle(ISerializationContext context, Triangle semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
