/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import shapes.myconstructor.ShapesRuntimeModule;
import shapes.myconstructor.ShapesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShapesIdeSetup extends ShapesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShapesRuntimeModule(), new ShapesIdeModule()));
	}
	
}
