/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.ui;

import com.google.inject.Injector;
import diro.geodes.vcsFeatures.ui.internal.VcsFeaturesActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VcsFeaturesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VcsFeaturesActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VcsFeaturesActivator activator = VcsFeaturesActivator.getInstance();
		return activator != null ? activator.getInjector(VcsFeaturesActivator.DIRO_GEODES_VCSFEATURES) : null;
	}

}
