/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import shapes.myconstructor.ui.internal.MyconstructorActivator;

public class ShapesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyconstructorActivator.getInstance().getInjector("shapes.myconstructor.Shapes");
	}

}
