/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShapesScopeProvider extends DelegatingScopeProvider {
}
