<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lEV4REC" nsURI="http://www.example.org/lEV4REC" nsPrefix="lEV4REC">
  <eClassifiers xsi:type="ecore:EClass" name="RecommenderSpecification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendercomponent" lowerBound="1"
        eType="#//RecommenderComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportinglibrary" lowerBound="1"
        eType="#//SupportingLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommenderComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasetcomponent" lowerBound="1"
        eType="#//DatasetComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessingcomponent"
        lowerBound="1" eType="#//PreprocessingComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationcomponent"
        lowerBound="1" eType="#//PresentationComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationcomponent" lowerBound="1"
        eType="#//EvaluationComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendationsetting"
        upperBound="-1" eType="#//RecommendationSetting"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportingLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithmlibrary" lowerBound="1"
        eType="#//AlgorithmLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasetlibrary" lowerBound="1"
        eType="#//DatasetLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationlibrary" lowerBound="1"
        eType="#//PresentationLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationlibrary" lowerBound="1"
        eType="#//EvaluationLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessinglibrary" lowerBound="1"
        eType="#//PreprocessingLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasettype" lowerBound="1"
        eType="#//DatasetType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessingComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessingTechnique"
        upperBound="-1" eType="#//PreprocessingTechnique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ideplugin" lowerBound="1"
        eType="#//IDEPlugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossfold" eType="#//CrossFold"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisedDataset" eSuperTypes="#//DatasetType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datastructure" eType="#//DataStructure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="independantVariable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependantVariable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDEPlugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="CrossFold">
    <eStructuralFeatures xsi:type="ecore:EReference" name="splittingkfold" lowerBound="1"
        eType="#//SplittingKFold" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SplittingKFold"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprise" lowerBound="1"
        eType="#//Surprise" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pandas" eType="#//Pandas"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idelibrary" lowerBound="1"
        eType="#//IDELibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisesplit" lowerBound="1"
        eType="#//SurpriseSplit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessingLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisepreprocessing"
        eType="#//SurprisePreprocessing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Surprise"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pandas"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDELibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipseplugin" lowerBound="1"
        eType="#//EclipsePlugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EclipsePlugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="SurpriseSplit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisecrossfold" lowerBound="1"
        eType="#//SurpriseCrossFold" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SurpriseCrossFold"/>
  <eClassifiers xsi:type="ecore:EClass" name="SurprisePreprocessing"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextualContainer" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Column" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARFF" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Variable" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMissingValueAllowed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableType" lowerBound="1"
        eType="#//VariableType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasource" lowerBound="1"
        eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessingcomponent"
        eType="#//PreprocessingComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="CategoricalData" value="2"/>
    <eLiterals name="Integer" value="3"/>
    <eLiterals name="Float" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PreprocessingTechnique">
    <eLiterals name="DUPLICATES_REMOVAL" literal="DUPLICATES_REMOVAL"/>
    <eLiterals name="NORMALIZATION" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeRepository" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationChannel" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BugTrackingSystem" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//Graph"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationSetting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringRS" eSuperTypes="lowcoders.ecore#//RecommendationSystem #//RecommenderComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filteringRSAlgorithm" eType="ecore:EEnum lowcoders.ecore#//FilteringRSAlgorithm"
        defaultValueLiteral="USER_BASED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarityCalculator" eType="ecore:EEnum lowcoders.ecore#//SimilarityFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cutoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neighborhood" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FilteringRSAlgorithm">
    <eLiterals name="CONTENT_BASED"/>
    <eLiterals name="DEMOGRAPHIC" value="1"/>
    <eLiterals name="USER_BASED" value="2"/>
    <eLiterals name="ITEM_BASED" value="3"/>
    <eLiterals name="CONTEXT_AWARE" value="4"/>
    <eLiterals name="HYBRID" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimilarityFunction">
    <eLiterals name="COSINE_SIMILARITY"/>
    <eLiterals name="JACCARD_DISTANCE" value="1"/>
    <eLiterals name="WORD_EMBEDDINGS" value="2"/>
    <eLiterals name="LEVENSHTEIN_DISTANCE" value="3"/>
    <eLiterals name="SVD" value="4"/>
    <eLiterals name="GRAPH_BASED" value="5"/>
    <eLiterals name="MSD" value="6" literal="MSD"/>
    <eLiterals name="EUCLIDEAN_DISTANCE" value="7"/>
  </eClassifiers>
</ecore:EPackage>
