/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.ui.tests;

import com.google.inject.Injector;
import diro.geodes.vcsFeatures.ui.internal.VcsFeaturesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class VcsFeaturesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VcsFeaturesActivator.getInstance().getInjector("diro.geodes.VcsFeatures");
	}

}
