/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ShapesGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ShapeConstructorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.ShapeConstructor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cShapeConstructorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cShapeConstructorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cShapeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cShapeAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cShapeShapeParserRuleCall_4_2_0 = (RuleCall)cShapeAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cShapeAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cShapeShapeParserRuleCall_4_3_1_0 = (RuleCall)cShapeAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ShapeConstructor returns ShapeConstructor:
		//    {ShapeConstructor}
		//    'ShapeConstructor'
		//    name=EString
		//    '{'
		//        ('shape' '{' shape+=Shape ( "," shape+=Shape)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ShapeConstructor}
		//'ShapeConstructor'
		//name=EString
		//'{'
		//    ('shape' '{' shape+=Shape ( "," shape+=Shape)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ShapeConstructor}
		public Action getShapeConstructorAction_0() { return cShapeConstructorAction_0; }
		
		//'ShapeConstructor'
		public Keyword getShapeConstructorKeyword_1() { return cShapeConstructorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('shape' '{' shape+=Shape ( "," shape+=Shape)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'shape'
		public Keyword getShapeKeyword_4_0() { return cShapeKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//shape+=Shape
		public Assignment getShapeAssignment_4_2() { return cShapeAssignment_4_2; }
		
		//Shape
		public RuleCall getShapeShapeParserRuleCall_4_2_0() { return cShapeShapeParserRuleCall_4_2_0; }
		
		//( "," shape+=Shape)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//shape+=Shape
		public Assignment getShapeAssignment_4_3_1() { return cShapeAssignment_4_3_1; }
		
		//Shape
		public RuleCall getShapeShapeParserRuleCall_4_3_1_0() { return cShapeShapeParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ShapeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.Shape");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCircleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRectangleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTriangleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Shape returns Shape:
		//    Circle | Rectangle | Triangle;
		@Override public ParserRule getRule() { return rule; }
		
		//Circle | Rectangle | Triangle
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Circle
		public RuleCall getCircleParserRuleCall_0() { return cCircleParserRuleCall_0; }
		
		//Rectangle
		public RuleCall getRectangleParserRuleCall_1() { return cRectangleParserRuleCall_1; }
		
		//Triangle
		public RuleCall getTriangleParserRuleCall_2() { return cTriangleParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class CircleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.Circle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCircleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCircleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRadiusKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRadiusAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRadiusEIntParserRuleCall_4_1_0 = (RuleCall)cRadiusAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Circle returns Circle:
		//    {Circle}
		//    'Circle'
		//    name=EString
		//    '{'
		//        ('radius' radius=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Circle}
		//'Circle'
		//name=EString
		//'{'
		//    ('radius' radius=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Circle}
		public Action getCircleAction_0() { return cCircleAction_0; }
		
		//'Circle'
		public Keyword getCircleKeyword_1() { return cCircleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('radius' radius=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'radius'
		public Keyword getRadiusKeyword_4_0() { return cRadiusKeyword_4_0; }
		
		//radius=EInt
		public Assignment getRadiusAssignment_4_1() { return cRadiusAssignment_4_1; }
		
		//EInt
		public RuleCall getRadiusEIntParserRuleCall_4_1_0() { return cRadiusEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RectangleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.Rectangle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRectangleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRectangleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLengthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLengthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLengthEIntParserRuleCall_4_1_0 = (RuleCall)cLengthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWidthKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cWidthAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_5_1_0 = (RuleCall)cWidthAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Rectangle returns Rectangle:
		//    {Rectangle}
		//    'Rectangle'
		//    name=EString
		//    '{'
		//        ('length' length=EInt)?
		//        ('width' width=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Rectangle}
		//'Rectangle'
		//name=EString
		//'{'
		//    ('length' length=EInt)?
		//    ('width' width=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Rectangle}
		public Action getRectangleAction_0() { return cRectangleAction_0; }
		
		//'Rectangle'
		public Keyword getRectangleKeyword_1() { return cRectangleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('length' length=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'length'
		public Keyword getLengthKeyword_4_0() { return cLengthKeyword_4_0; }
		
		//length=EInt
		public Assignment getLengthAssignment_4_1() { return cLengthAssignment_4_1; }
		
		//EInt
		public RuleCall getLengthEIntParserRuleCall_4_1_0() { return cLengthEIntParserRuleCall_4_1_0; }
		
		//('width' width=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'width'
		public Keyword getWidthKeyword_5_0() { return cWidthKeyword_5_0; }
		
		//width=EInt
		public Assignment getWidthAssignment_5_1() { return cWidthAssignment_5_1; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_5_1_0() { return cWidthEIntParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TriangleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.Triangle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTriangleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTriangleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAEIntParserRuleCall_4_1_0 = (RuleCall)cAAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBEIntParserRuleCall_5_1_0 = (RuleCall)cBAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCEIntParserRuleCall_6_1_0 = (RuleCall)cCAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Triangle returns Triangle:
		//    {Triangle}
		//    'Triangle'
		//    name=EString
		//    '{'
		//        ('a' a=EInt)?
		//        ('b' b=EInt)?
		//        ('c' c=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Triangle}
		//'Triangle'
		//name=EString
		//'{'
		//    ('a' a=EInt)?
		//    ('b' b=EInt)?
		//    ('c' c=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Triangle}
		public Action getTriangleAction_0() { return cTriangleAction_0; }
		
		//'Triangle'
		public Keyword getTriangleKeyword_1() { return cTriangleKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('a' a=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'a'
		public Keyword getAKeyword_4_0() { return cAKeyword_4_0; }
		
		//a=EInt
		public Assignment getAAssignment_4_1() { return cAAssignment_4_1; }
		
		//EInt
		public RuleCall getAEIntParserRuleCall_4_1_0() { return cAEIntParserRuleCall_4_1_0; }
		
		//('b' b=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'b'
		public Keyword getBKeyword_5_0() { return cBKeyword_5_0; }
		
		//b=EInt
		public Assignment getBAssignment_5_1() { return cBAssignment_5_1; }
		
		//EInt
		public RuleCall getBEIntParserRuleCall_5_1_0() { return cBEIntParserRuleCall_5_1_0; }
		
		//('c' c=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'c'
		public Keyword getCKeyword_6_0() { return cCKeyword_6_0; }
		
		//c=EInt
		public Assignment getCAssignment_6_1() { return cCAssignment_6_1; }
		
		//EInt
		public RuleCall getCEIntParserRuleCall_6_1_0() { return cCEIntParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "shapes.myconstructor.Shapes.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final ShapeConstructorElements pShapeConstructor;
	private final ShapeElements pShape;
	private final EStringElements pEString;
	private final CircleElements pCircle;
	private final RectangleElements pRectangle;
	private final TriangleElements pTriangle;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ShapesGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pShapeConstructor = new ShapeConstructorElements();
		this.pShape = new ShapeElements();
		this.pEString = new EStringElements();
		this.pCircle = new CircleElements();
		this.pRectangle = new RectangleElements();
		this.pTriangle = new TriangleElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("shapes.myconstructor.Shapes".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ShapeConstructor returns ShapeConstructor:
	//    {ShapeConstructor}
	//    'ShapeConstructor'
	//    name=EString
	//    '{'
	//        ('shape' '{' shape+=Shape ( "," shape+=Shape)* '}' )?
	//    '}';
	public ShapeConstructorElements getShapeConstructorAccess() {
		return pShapeConstructor;
	}
	
	public ParserRule getShapeConstructorRule() {
		return getShapeConstructorAccess().getRule();
	}
	
	//Shape returns Shape:
	//    Circle | Rectangle | Triangle;
	public ShapeElements getShapeAccess() {
		return pShape;
	}
	
	public ParserRule getShapeRule() {
		return getShapeAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Circle returns Circle:
	//    {Circle}
	//    'Circle'
	//    name=EString
	//    '{'
	//        ('radius' radius=EInt)?
	//    '}';
	public CircleElements getCircleAccess() {
		return pCircle;
	}
	
	public ParserRule getCircleRule() {
		return getCircleAccess().getRule();
	}
	
	//Rectangle returns Rectangle:
	//    {Rectangle}
	//    'Rectangle'
	//    name=EString
	//    '{'
	//        ('length' length=EInt)?
	//        ('width' width=EInt)?
	//    '}';
	public RectangleElements getRectangleAccess() {
		return pRectangle;
	}
	
	public ParserRule getRectangleRule() {
		return getRectangleAccess().getRule();
	}
	
	//Triangle returns Triangle:
	//    {Triangle}
	//    'Triangle'
	//    name=EString
	//    '{'
	//        ('a' a=EInt)?
	//        ('b' b=EInt)?
	//        ('c' c=EInt)?
	//    '}';
	public TriangleElements getTriangleAccess() {
		return pTriangle;
	}
	
	public ParserRule getTriangleRule() {
		return getTriangleAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
