/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import diro.geodes.VcsFeaturesRuntimeModule;
import diro.geodes.VcsFeaturesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VcsFeaturesIdeSetup extends VcsFeaturesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VcsFeaturesRuntimeModule(), new VcsFeaturesIdeModule()));
	}
	
}
