/**
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import shapes.Shape;
import shapes.ShapeConstructor;
import shapes.myconstructor.services.ShapesGrammarAccess;

@SuppressWarnings("all")
public class ShapesFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ShapesGrammarAccess _shapesGrammarAccess;

  protected void _format(final ShapeConstructor shapeConstructor, @Extension final IFormattableDocument document) {
    EList<Shape> _shape = shapeConstructor.getShape();
    for (final Shape shape : _shape) {
      document.<Shape>format(shape);
    }
  }

  public void format(final Object shapeConstructor, final IFormattableDocument document) {
    if (shapeConstructor instanceof XtextResource) {
      _format((XtextResource)shapeConstructor, document);
      return;
    } else if (shapeConstructor instanceof ShapeConstructor) {
      _format((ShapeConstructor)shapeConstructor, document);
      return;
    } else if (shapeConstructor instanceof EObject) {
      _format((EObject)shapeConstructor, document);
      return;
    } else if (shapeConstructor == null) {
      _format((Void)null, document);
      return;
    } else if (shapeConstructor != null) {
      _format(shapeConstructor, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(shapeConstructor, document).toString());
    }
  }
}
