/**
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.generator;

import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import shapes.Circle;
import shapes.Rectangle;
import shapes.Triangle;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ShapesGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("***************************************************************************************************************");
    _builder.newLine();
    _builder.append("Circles:");
    _builder.newLine();
    {
      Iterable<Circle> _iterable = IteratorExtensions.<Circle>toIterable(Iterators.<Circle>filter(resource.getAllContents(), Circle.class));
      for(final Circle circle : _iterable) {
        _builder.append("Name: ");
        String _name = circle.getName();
        _builder.append(_name);
        _builder.append(" Radius: ");
        int _radius = circle.getRadius();
        _builder.append(_radius);
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("***************************************************************************************************************");
    _builder.newLine();
    _builder.append("Rectangles:");
    _builder.newLine();
    {
      Iterable<Rectangle> _iterable_1 = IteratorExtensions.<Rectangle>toIterable(Iterators.<Rectangle>filter(resource.getAllContents(), Rectangle.class));
      for(final Rectangle rect : _iterable_1) {
        _builder.append("Name: ");
        String _name_1 = rect.getName();
        _builder.append(_name_1);
        _builder.append(" Length: ");
        int _length = rect.getLength();
        _builder.append(_length);
        _builder.append(" Width: ");
        int _length_1 = rect.getLength();
        _builder.append(_length_1);
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("***************************************************************************************************************");
    _builder.newLine();
    _builder.append("Triangles:");
    _builder.newLine();
    {
      Iterable<Triangle> _iterable_2 = IteratorExtensions.<Triangle>toIterable(Iterators.<Triangle>filter(resource.getAllContents(), Triangle.class));
      for(final Triangle tri : _iterable_2) {
        _builder.append("Name: ");
        String _name_2 = tri.getName();
        _builder.append(_name_2);
        _builder.append(" A: ");
        int _a = tri.getA();
        _builder.append(_a);
        _builder.append(" B: ");
        int _b = tri.getB();
        _builder.append(_b);
        _builder.append(" C: ");
        int _c = tri.getC();
        _builder.append(_c);
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("***************************************************************************************************************");
    _builder.newLine();
    fsa.generateFile("AllShapes.txt", _builder);
  }
}
