/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ShapesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("shapes/myconstructor/parser/antlr/internal/InternalShapes.tokens");
	}
}
