/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import shapes.myconstructor.parser.antlr.internal.InternalShapesParser;
import shapes.myconstructor.services.ShapesGrammarAccess;

public class ShapesParser extends AbstractAntlrParser {

	@Inject
	private ShapesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShapesParser createParser(XtextTokenStream stream) {
		return new InternalShapesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ShapeConstructor";
	}

	public ShapesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShapesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
