/**
 *
 * $Id$
 */
package eCommercePMM.validation;


/**
 * A sample validator interface for {@link eCommercePMM.Discount}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiscountValidator {
	boolean validate();

	boolean validateDiscountID(String value);
	boolean validateAmount(double value);
}
