/**
 *
 * $Id$
 */
package eCommercePMM.validation;

import eCommercePMM.ItemCatalog;
import eCommercePMM.PaymentType;
import eCommercePMM.ShoppingCart;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eCommercePMM.ECommerce}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ECommerceValidator {
	boolean validate();

	boolean validateProductcatalog(EList<ItemCatalog> value);
	boolean validateShoppingcart(EList<ShoppingCart> value);
	boolean validatePaymenttype(EList<PaymentType> value);
	boolean validateName(String value);
}
