/**
 *
 * $Id$
 */
package eCommercePMM.validation;

import eCommercePMM.Item;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eCommercePMM.ItemCatalog}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemCatalogValidator {
	boolean validate();

	boolean validateCatalogID(String value);
	boolean validateItem(EList<Item> value);
}
