/**
 *
 * $Id$
 */
package eCommercePMM.validation;

import eCommercePMM.Discount;
import eCommercePMM.PaymentType;

/**
 * A sample validator interface for {@link eCommercePMM.ShoppingCart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShoppingCartValidator {
	boolean validate();

	boolean validateDiscount(Discount value);
	boolean validatePaymenttype(PaymentType value);
	boolean validateCartID(String value);
}
