/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVcsFeaturesScopeProvider extends DelegatingScopeProvider {
}
