<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="VCSFeatures" nsPrefix="VCSFeatures" nsURI="http://www.example.org/VCSFeatures" xmi:version="2.0">
    <eClassifiers name="VCSFeatures" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="VCSFeatures"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//VCSFeatures" name="Commands" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Commands"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//Commands" name="HighLevelCommands" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="HighLevelCommands"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//Commands" name="LowLevelCommands" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="LowLevelCommands"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Add" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Add"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Checkout" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Checkout"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="CheckoutCreate" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="CheckoutCreate"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Clone" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Clone"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Commit" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Commit"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="CreateBranch" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="CreateBranch"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Fetch" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Fetch"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Init" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Init"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Open" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Open"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Pull" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Pull"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="Push" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Push"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//LowLevelCommands" name="RemoteAdd" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="RemoteAdd"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//Commands" name="MergeStrategy" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="MergeStrategy"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//MergeStrategy" name="GitDiff" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="GitDiff"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//VCSFeatures" name="History" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="History"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//History" name="BranchingStyle" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="BranchingStyle"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//BranchingStyle" name="MultiBranch" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="MultiBranch"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//MultiBranch" name="InfiniteBranches" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="InfiniteBranches"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//History" name="Timestamping" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Timestamping"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//Timestamping" name="CommitHash" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="CommitHash"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//VCSFeatures" name="VersionUnit" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="VersionUnit"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//VersionUnit" name="File" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="File"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//VersionUnit" name="Element" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Element"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//VersionUnit" name="Line" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Line"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//VCSFeatures" name="CollaborationStyle" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="CollaborationStyle"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//CollaborationStyle" name="Remote" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Remote"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#//VCSFeatures" name="Database" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="Database"/>
                
        </eAnnotations>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//Database" name="XMI" xsi:type="ecore:EClass">
        <eAnnotations source="FM2UMM">
                  
            <details key="feature" value="XMI"/>
                
        </eAnnotations>
        <eAnnotations source="FM2UMM">
                  
            <details key="leaf" value="true"/>
                
        </eAnnotations>
    </eClassifiers>
</ecore:EPackage>
