/**
 *
 * $Id$
 */
package shapes.validation;

import org.eclipse.emf.common.util.EList;

import shapes.Shape;

/**
 * A sample validator interface for {@link shapes.ShapeConstructor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShapeConstructorValidator {
	boolean validate();

	boolean validateShape(EList<Shape> value);
	boolean validateName(String value);
}
