package configs;

import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import vcsFeaturesMM.HighLevelCommand;
import vcsFeaturesMM.LowLevelCommand;
import vcsFeaturesMM.VCSFeatures;

@SuppressWarnings("all")
public class PluginGenerator implements ConfigGenerator {
  @Override
  public CharSequence generate(final Resource resource) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<?eclipse version=\"3.4\"?>");
    _builder.newLine();
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("id=\"product\"");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.core.runtime.products\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<product");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("application=\"org.eclipse.e4.ui.workbench.swt.E4Application\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"");
    String _lowerCase = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName().toLowerCase();
    _builder.append(_lowerCase, "            ");
    _builder.append("\">");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("<property");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("name=\"applicationCSS\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("value=\"platform:/plugin/");
    String _name = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name, "               ");
    _builder.append("/css/default.css\">");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</property>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</product>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"");
    String _name_1 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name_1, "            ");
    _builder.append(".commands.category\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("name=\"Sample Category\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"");
    String _name_2 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name_2, "            ");
    _builder.append(".uiCommands\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("name=\"UI Commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"");
    String _name_3 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name_3, "            ");
    _builder.append(".commands.category\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("description=\"This command is used to rename JGit commands (give aliases)\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"");
    String _name_4 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name_4, "            ");
    _builder.append(".commands.renameCommand\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("name=\"Rename Command\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc : _iterable) {
        _builder.append("      ");
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("categoryId=\"");
        String _name_5 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_5, "            ");
        _builder.append(".uiCommands\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("id=\"");
        String _name_6 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_6, "            ");
        _builder.append(".");
        String _name_7 = llc.getCommand().getName();
        _builder.append(_name_7, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("name=\"");
        String _name_8 = llc.getName();
        _builder.append(_name_8, "            ");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    {
      Iterable<HighLevelCommand> _iterable_1 = IteratorExtensions.<HighLevelCommand>toIterable(Iterators.<HighLevelCommand>filter(resource.getAllContents(), HighLevelCommand.class));
      for(final HighLevelCommand hlc : _iterable_1) {
        _builder.append("      ");
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("\t\t");
        _builder.append("categoryId=\"");
        String _name_9 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_9, "      \t\t");
        _builder.append(".uiCommands\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("\t\t");
        _builder.append("id=\"");
        String _name_10 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_10, "      \t\t");
        _builder.append(".");
        String _name_11 = hlc.getName();
        String _plus = (_name_11 + "Command");
        _builder.append(_plus, "      \t\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("\t\t");
        _builder.append("name=\"");
        String _name_12 = hlc.getName();
        _builder.append(_name_12, "      \t\t");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.handlers\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.RenameHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"");
    String _name_13 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
    _builder.append(_name_13, "            ");
    _builder.append(".commands.renameCommand\">");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable_2 = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc_1 : _iterable_2) {
        _builder.append("<handler\t\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("class=\"handlers.");
        String _get = llc_1.getCommand().getName().split("Command")[0];
        String _plus_1 = (_get + "Handler");
        _builder.append(_plus_1, "\t\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("commandId=\"");
        String _name_14 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_14, "\t\t");
        _builder.append(".");
        String _name_15 = llc_1.getCommand().getName();
        _builder.append(_name_15, "\t\t");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("</handler>");
        _builder.newLine();
      }
    }
    {
      Iterable<HighLevelCommand> _iterable_3 = IteratorExtensions.<HighLevelCommand>toIterable(Iterators.<HighLevelCommand>filter(resource.getAllContents(), HighLevelCommand.class));
      for(final HighLevelCommand hlc_1 : _iterable_3) {
        _builder.append("<handler\t\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("class=\"handlers.");
        String _name_16 = hlc_1.getName();
        String _plus_2 = (_name_16 + "Handler");
        _builder.append(_plus_2, "\t\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("commandId=\"");
        String _name_17 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_17, "\t\t");
        _builder.append(".");
        String _name_18 = hlc_1.getName();
        String _plus_3 = (_name_18 + "Command");
        _builder.append(_plus_3, "\t\t");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("</handler>");
        _builder.newLine();
      }
    }
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("point=\"org.eclipse.ui.menus\">");
    _builder.newLine();
    _builder.append("   \t\t");
    _builder.append("<menuContribution");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("allPopups=\"false\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("locationURI=\"popup:org.eclipse.ui.popup.any?after=additions\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<menu");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("id=\"org.eclipse.ui.navigator.ProjectExplorer.VCSBuilder\"");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("label=\"VCSBuilder\">");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable_4 = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc_2 : _iterable_4) {
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("commandId=\"");
        String _name_19 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_19, "      ");
        _builder.append(".");
        String _name_20 = llc_2.getCommand().getName();
        _builder.append(_name_20, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("label=\"");
        String _name_21 = llc_2.getName();
        _builder.append(_name_21, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("style=\"push\">");
        _builder.newLine();
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    {
      Iterable<HighLevelCommand> _iterable_5 = IteratorExtensions.<HighLevelCommand>toIterable(Iterators.<HighLevelCommand>filter(resource.getAllContents(), HighLevelCommand.class));
      for(final HighLevelCommand hlc_2 : _iterable_5) {
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("commandId=\"");
        String _name_22 = IteratorExtensions.<VCSFeatures>head(Iterators.<VCSFeatures>filter(resource.getAllContents(), VCSFeatures.class)).getName();
        _builder.append(_name_22, "      ");
        _builder.append(".");
        String _name_23 = hlc_2.getName();
        String _plus_4 = (_name_23 + "Command");
        _builder.append(_plus_4, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("label=\"");
        String _name_24 = hlc_2.getName();
        _builder.append(_name_24, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("style=\"push\">");
        _builder.newLine();
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    _builder.append("            ");
    _builder.append("</menu>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</menuContribution>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
