<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ReLiS" nsURI="http://www.example.org/ReLiS" nsPrefix="ReLiS">
  <eClassifiers xsi:type="ecore:EClass" name="ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ReLiS"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screening" eType="#//Screening"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qa" eType="#//QA" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataextraction" lowerBound="1"
        eType="#//DataExtraction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synthesis" eType="#//Synthesis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Screening"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phase" lowerBound="1" upperBound="-1"
        eType="#//Phase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phase">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Phase"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QA">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="QA"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answer" lowerBound="1"
        upperBound="-1" eType="#//Answer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Question"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Answer"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataExtraction">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DataExtraction"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        upperBound="-1" eType="#//Category" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Category"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryType" abstract="true" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CategoryType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeCategory" abstract="true" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FreeCategory"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//FreeCategory">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Note"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="StaticCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentDynamicCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="IndependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentDynamicCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synthesis">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Synthesis"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chart" lowerBound="1" upperBound="-1"
        eType="#//Chart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Chart"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareGraph?">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CompareGraph"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
