<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ReLiS" nsURI="http://www.example.org/ReLiS" nsPrefix="ReLiS">
  <eClassifiers xsi:type="ecore:EClass" name="ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ReLiS"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screening" abstract="true" eSuperTypes="#//ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Screening"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Criteria" abstract="true" eSuperTypes="#//Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Criteria"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusion?" eSuperTypes="#//Criteria">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Inclusion"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusion?" eSuperTypes="#//Criteria">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Exclusion"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleReviewers" eSuperTypes="#//Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="MultipleReviewers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflict" lowerBound="-2"
        upperBound="-2" eType="#//Conflict" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conflict" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Conflict"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictDetection" abstract="true" eSuperTypes="#//Conflict">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ConflictDetection"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeExclude?" eSuperTypes="#//ConflictDetection">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="IncludeExclude"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictResolution" abstract="true"
      eSuperTypes="#//Conflict">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ConflictResolution"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Majority?" eSuperTypes="#//ConflictResolution">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Majority"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validation" abstract="true" eSuperTypes="#//Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Validation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentMode" abstract="true" eSuperTypes="#//Validation">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="AssignmentMode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Veto?" eSuperTypes="#//AssignmentMode">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Veto"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phase" eSuperTypes="#//Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Phase"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="-2"
        upperBound="-2" eType="#//Field?" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field?">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Field"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QA" abstract="true" eSuperTypes="#//ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="QA"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question?" eSuperTypes="#//QA">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Question"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer?" eSuperTypes="#//QA">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Answer"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataExtraction" abstract="true" eSuperTypes="#//ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DataExtraction"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true" eSuperTypes="#//DataExtraction">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Category"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryType" abstract="true" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CategoryType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FreeCategory"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="string" lowerBound="-2"
        upperBound="-2" eType="#//String?" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String?">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="String"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note?" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Note"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticCategory?" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="StaticCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentDynamicCategory?" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="IndependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentDynamicCategory?" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subcategroies?" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Subcategroies"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryCategory?" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="MandatoryCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multivalued?" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Multivalued"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialValue?" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="InitialValue"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synthesis" abstract="true" eSuperTypes="#//ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Synthesis"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareGraph?" eSuperTypes="#//Synthesis">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CompareGraph"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//Synthesis">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Type"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line?" eSuperTypes="#//Type">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Line"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
