<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ReLiS" nsURI="http://www.example.org/ReLiS" nsPrefix="ReLiS">
  <eClassifiers xsi:type="ecore:EClass" name="ReLiS">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ReLiS"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screening" eType="#//Screening"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qa" eType="#//QA" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataextraction" lowerBound="1"
        eType="#//DataExtraction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synthesis" eType="#//Synthesis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screening">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Screening"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" lowerBound="-2"
        upperBound="-2" eType="#//Criteria" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplereviewers" lowerBound="-2"
        upperBound="-2" eType="#//MultipleReviewers" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" lowerBound="-2"
        upperBound="-2" eType="#//Validation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phase" lowerBound="1" upperBound="-1"
        eType="#//Phase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Criteria" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Criteria"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusion?" eSuperTypes="#//Criteria">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Inclusion"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusion?" eSuperTypes="#//Criteria">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Exclusion"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleReviewers">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="MultipleReviewers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conflict" lowerBound="-2"
        upperBound="-2" eType="#//Conflict" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conflict" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Conflict"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictType" abstract="true" eSuperTypes="#//Conflict">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ConflictType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeExclude?" eSuperTypes="#//ConflictType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="IncludeExclude"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictResolution" abstract="true"
      eSuperTypes="#//Conflict">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ConflictResolution"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Majority?" eSuperTypes="#//ConflictResolution">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Majority"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validation">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Validation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentmode" lowerBound="-2"
        upperBound="-2" eType="#//AssignmentMode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentMode" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="AssignmentMode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Veto?" eSuperTypes="#//AssignmentMode">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Veto"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phase">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Phase"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="-2"
        upperBound="-2" eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Field"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title?" eSuperTypes="#//Field">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Title"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract?" eSuperTypes="#//Field">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Abstract"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paper?" eSuperTypes="#//Field">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Paper"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author?" eSuperTypes="#//Field">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Author"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference?" eSuperTypes="#//Field">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Reference"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QA">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="QA"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answer" lowerBound="1"
        upperBound="-1" eType="#//Answer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Question"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Answer"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataExtraction">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DataExtraction"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        upperBound="-1" eType="#//Category" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Category"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryType" abstract="true" eSuperTypes="#//Category">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CategoryType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeCategory" abstract="true" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FreeCategory"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//FreeCategory">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Note"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" abstract="true" eSuperTypes="#//FreeCategory">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="SimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String?" eSuperTypes="#//SimpleType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="String"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="StaticCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentDynamicCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="IndependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentDynamicCategory" eSuperTypes="#//CategoryType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DependentDynamicCategory"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synthesis">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Synthesis"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chart" lowerBound="1" upperBound="-1"
        eType="#//Chart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Chart"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charttype" lowerBound="-2"
        upperBound="-2" eType="#//ChartType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparegraph" lowerBound="-2"
        upperBound="-2" eType="#//CompareGraph?" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartType" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="ChartType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line?" eSuperTypes="#//ChartType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Line"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareGraph?">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="CompareGraph"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
