/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import shapes.myconstructor.ide.contentassist.antlr.internal.InternalShapesParser;
import shapes.myconstructor.services.ShapesGrammarAccess;

public class ShapesParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ShapesGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ShapesGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getShapeAccess().getAlternatives(), "rule__Shape__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getShapeConstructorAccess().getGroup(), "rule__ShapeConstructor__Group__0");
			builder.put(grammarAccess.getShapeConstructorAccess().getGroup_4(), "rule__ShapeConstructor__Group_4__0");
			builder.put(grammarAccess.getShapeConstructorAccess().getGroup_4_3(), "rule__ShapeConstructor__Group_4_3__0");
			builder.put(grammarAccess.getCircleAccess().getGroup(), "rule__Circle__Group__0");
			builder.put(grammarAccess.getCircleAccess().getGroup_4(), "rule__Circle__Group_4__0");
			builder.put(grammarAccess.getRectangleAccess().getGroup(), "rule__Rectangle__Group__0");
			builder.put(grammarAccess.getRectangleAccess().getGroup_4(), "rule__Rectangle__Group_4__0");
			builder.put(grammarAccess.getRectangleAccess().getGroup_5(), "rule__Rectangle__Group_5__0");
			builder.put(grammarAccess.getTriangleAccess().getGroup(), "rule__Triangle__Group__0");
			builder.put(grammarAccess.getTriangleAccess().getGroup_4(), "rule__Triangle__Group_4__0");
			builder.put(grammarAccess.getTriangleAccess().getGroup_5(), "rule__Triangle__Group_5__0");
			builder.put(grammarAccess.getTriangleAccess().getGroup_6(), "rule__Triangle__Group_6__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getShapeConstructorAccess().getNameAssignment_2(), "rule__ShapeConstructor__NameAssignment_2");
			builder.put(grammarAccess.getShapeConstructorAccess().getShapeAssignment_4_2(), "rule__ShapeConstructor__ShapeAssignment_4_2");
			builder.put(grammarAccess.getShapeConstructorAccess().getShapeAssignment_4_3_1(), "rule__ShapeConstructor__ShapeAssignment_4_3_1");
			builder.put(grammarAccess.getCircleAccess().getNameAssignment_2(), "rule__Circle__NameAssignment_2");
			builder.put(grammarAccess.getCircleAccess().getRadiusAssignment_4_1(), "rule__Circle__RadiusAssignment_4_1");
			builder.put(grammarAccess.getRectangleAccess().getNameAssignment_2(), "rule__Rectangle__NameAssignment_2");
			builder.put(grammarAccess.getRectangleAccess().getLengthAssignment_4_1(), "rule__Rectangle__LengthAssignment_4_1");
			builder.put(grammarAccess.getRectangleAccess().getWidthAssignment_5_1(), "rule__Rectangle__WidthAssignment_5_1");
			builder.put(grammarAccess.getTriangleAccess().getNameAssignment_2(), "rule__Triangle__NameAssignment_2");
			builder.put(grammarAccess.getTriangleAccess().getAAssignment_4_1(), "rule__Triangle__AAssignment_4_1");
			builder.put(grammarAccess.getTriangleAccess().getBAssignment_5_1(), "rule__Triangle__BAssignment_5_1");
			builder.put(grammarAccess.getTriangleAccess().getCAssignment_6_1(), "rule__Triangle__CAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ShapesGrammarAccess grammarAccess;

	@Override
	protected InternalShapesParser createParser() {
		InternalShapesParser result = new InternalShapesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ShapesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShapesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
