/*
 * generated by Xtext 2.32.0
 */
package diro.geodes;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VcsFeaturesStandaloneSetup extends VcsFeaturesStandaloneSetupGenerated {

	public static void doSetup() {
		new VcsFeaturesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
