/*
 * generated by Xtext 2.32.0
 */
package diro.geodes;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VcsFeaturesRuntimeModule extends AbstractVcsFeaturesRuntimeModule {
}
