/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.parser.antlr;

import com.google.inject.Inject;
import diro.geodes.parser.antlr.internal.InternalVcsFeaturesParser;
import diro.geodes.services.VcsFeaturesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VcsFeaturesParser extends AbstractAntlrParser {

	@Inject
	private VcsFeaturesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVcsFeaturesParser createParser(XtextTokenStream stream) {
		return new InternalVcsFeaturesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "VCSFeatures";
	}

	public VcsFeaturesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VcsFeaturesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
