/**
 *
 * $Id$
 */
package vcsFeaturesMM.validation;

import org.eclipse.emf.common.util.EList;

import vcsFeaturesMM.HighLevelCommand;
import vcsFeaturesMM.LowLevelCommand;
import vcsFeaturesMM.MergeStrategy;

/**
 * A sample validator interface for {@link vcsFeaturesMM.Commands}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommandsValidator {
	boolean validate();

	boolean validateMergeStrategy(MergeStrategy value);
	boolean validateHighlevelcommand(EList<HighLevelCommand> value);
	boolean validateLowlevelcommand(EList<LowLevelCommand> value);
}
