/**
 *
 * $Id$
 */
package vcsFeaturesMM.validation;

import vcsFeaturesMM.LabelType;

/**
 * A sample validator interface for {@link vcsFeaturesMM.History}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HistoryValidator {
	boolean validate();

	boolean validateLabelType(LabelType value);
	boolean validateCommitHistoryRange(int value);

	boolean validateNumberOfBranches(int value);

	boolean validateUniqueLabelString(String value);

	boolean validateCommitHistoryRange(Integer value);
	boolean validateNumberOfBranches(Integer value);
}
