/**
 *
 * $Id$
 */
package vcsFeaturesMM.validation;

import org.eclipse.emf.common.util.EList;

import vcsFeaturesMM.CollaborationStyle;
import vcsFeaturesMM.Commands;
import vcsFeaturesMM.Database;
import vcsFeaturesMM.History;
import vcsFeaturesMM.VersionUnit;

/**
 * A sample validator interface for {@link vcsFeaturesMM.VCSFeatures}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VCSFeaturesValidator {
	boolean validate();

	boolean validateCommands(EList<Commands> value);
	boolean validateHistory(EList<History> value);
	boolean validateVersionunit(EList<VersionUnit> value);
	boolean validateCollaborationstyle(EList<CollaborationStyle> value);
	boolean validateDatabase(EList<Database> value);
	boolean validateName(String value);
}
