/**
 *
 * $Id$
 */
package vcsFeaturesMM.validation;

import org.eclipse.emf.common.util.EList;

import vcsFeaturesMM.VersionUnitType;

/**
 * A sample validator interface for {@link vcsFeaturesMM.VersionUnit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VersionUnitValidator {
	boolean validate();

	boolean validateGranularity(EList<VersionUnitType> value);
}
