/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VcsFeaturesUiModule extends AbstractVcsFeaturesUiModule {

	public VcsFeaturesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
