/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ShapesUiModule extends AbstractShapesUiModule {

	public ShapesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
