<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lEV4REC" nsURI="http://www.example.org/lEV4REC" nsPrefix="lEV4REC">
  <eClassifiers xsi:type="ecore:EClass" name="RecommenderSpecification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendercomponent" lowerBound="1"
        eType="#//RecommenderComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportinglibrary" lowerBound="1"
        eType="#//SupportingLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommenderComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithmcomponent" lowerBound="1"
        eType="#//AlgorithmComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasetcomponent" lowerBound="1"
        eType="#//DatasetComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessingcomponent"
        lowerBound="1" eType="#//PreprocessingComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationcomponent"
        lowerBound="1" eType="#//PresentationComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationcomponent" lowerBound="1"
        eType="#//EvaluationComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportingLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithmlibrary" lowerBound="1"
        eType="#//AlgorithmLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasetlibrary" lowerBound="1"
        eType="#//DatasetLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationlibrary" lowerBound="1"
        eType="#//PresentationLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationlibrary" lowerBound="1"
        eType="#//EvaluationLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessinglibrary" lowerBound="1"
        eType="#//PreprocessingLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaborativefiltering"
        lowerBound="1" eType="#//CollaborativeFiltering" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datastructure" lowerBound="1"
        eType="#//DataStructure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasettype" lowerBound="1"
        eType="#//DatasetType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessingComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duplicatesremoval" eType="#//DuplicatesRemoval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="normalization" eType="#//Normalization"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ideplugin" lowerBound="1"
        eType="#//IDEPlugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossfold" eType="#//CrossFold"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborativeFiltering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userbased" lowerBound="1"
        eType="#//UserBased" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserBased"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrix" lowerBound="1"
        eType="#//Matrix" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superviseddataset" lowerBound="1"
        eType="#//SupervisedDataset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisedDataset"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuplicatesRemoval"/>
  <eClassifiers xsi:type="ecore:EClass" name="Normalization"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDEPlugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="CrossFold">
    <eStructuralFeatures xsi:type="ecore:EReference" name="splittingkfold" lowerBound="1"
        eType="#//SplittingKFold" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SplittingKFold"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprise" lowerBound="1"
        eType="#//Surprise" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pandas" eType="#//Pandas"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idelibrary" lowerBound="1"
        eType="#//IDELibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisesplit" lowerBound="1"
        eType="#//SurpriseSplit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessingLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisepreprocessing"
        eType="#//SurprisePreprocessing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Surprise"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pandas"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDELibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipseplugin" lowerBound="1"
        eType="#//EclipsePlugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EclipsePlugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="SurpriseSplit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surprisecrossfold" lowerBound="1"
        eType="#//SurpriseCrossFold" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SurpriseCrossFold"/>
  <eClassifiers xsi:type="ecore:EClass" name="SurprisePreprocessing"/>
</ecore:EPackage>
