/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import shapes.myconstructor.ui.internal.MyconstructorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ShapesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MyconstructorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MyconstructorActivator activator = MyconstructorActivator.getInstance();
		return activator != null ? activator.getInjector(MyconstructorActivator.SHAPES_MYCONSTRUCTOR_SHAPES) : null;
	}

}
