<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RecommenderSpecification" nsURI="http://www.example.org/RecommenderSpecification"
    nsPrefix="RecommenderSpecification">
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationSystem">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RecommenderSpecification"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" eType="#//PyLibType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" upperBound="-1"
        eType="#//RecommendationSetting" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//RecommendedItem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//RecommendationContext"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dataset" abstract="true">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DatasetComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasettype" lowerBound="1"
        upperBound="-1" eType="#//DatasetType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessing" upperBound="-1"
        eType="#//PreprocessingTechnique"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datasetManipulationLibrary"
        upperBound="-1" eType="#//DatasetManipulationLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datastructure" eType="#//DataStructure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBuiltIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure" eSuperTypes="#//NamedElement">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DataStructure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" eSuperTypes="#//DataStructure">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Matrix"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DatasetType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superviseddataset" lowerBound="1"
        upperBound="-1" eType="#//SupervisedDataset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisedDataset" eSuperTypes="#//Dataset">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="SupervisedDataset"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependantVariable" lowerBound="1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="EvaluationComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationTechnique" upperBound="-1"
        eType="#//ValidationTechnique" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baselines" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metrics" upperBound="-1"
        eType="#//Metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomSpltting" eSuperTypes="#//AutomatedValidation">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RandomSpltting"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserStudy">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="UserStudy"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UserStudyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysis" eType="#//UserStudyAnalysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationLayer" abstract="true" eSuperTypes="#//NamedElement">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="PresentationComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendations" eType="#//RecommendedItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RawOutcomes" eSuperTypes="#//PresentationLayer">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RawOutcomes"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//RawFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FeedbackComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressedFeedback" upperBound="-1"
        eType="#//Feedback" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//FeedbackLibType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//RecommendationContext"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feedback">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FeedBackType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//RecommendedItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridFeedback" eSuperTypes="#//Feedback">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Hybrid"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitFeedback" eSuperTypes="#//Feedback">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="HybridBased"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PreprocessingTechnique">
    <eLiterals name="Normalization"/>
    <eLiterals name="DuplicatesRemoval" value="1"/>
    <eLiterals name="MissingDataManipulation" value="2"/>
    <eLiterals name="FeatureScaling" value="3"/>
    <eLiterals name="Vectorization" value="4"/>
    <eLiterals name="NLP" value="5"/>
    <eLiterals name="TFIDF" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollaborativeFilteringAlgorithm">
    <eLiterals name="ItemBased"/>
    <eLiterals name="UserBased" value="1"/>
    <eLiterals name="ContentBased" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserStudyType">
    <eLiterals name="ControlledExperiment"/>
    <eLiterals name="Field_Studies" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackLibType">
    <eLiterals name="LightFM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatasetManipulationLibrary">
    <eLiterals name="Pandas"/>
    <eLiterals name="Numpy" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PyLibType">
    <eLiterals name="Surprise"/>
    <eLiterals name="Sklearn" value="1"/>
    <eLiterals name="Tensor_flow" value="2"/>
    <eLiterals name="Pytorch" value="3"/>
    <eLiterals name="Elliot" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidationLibrary">
    <eLiterals name="Surprise"/>
    <eLiterals name="Sklearn" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WebInterfaceLibrary">
    <eLiterals name="Flask"/>
    <eLiterals name="Spring" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VariableType"
        defaultValueLiteral="String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMissingValueAllowed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" lowerBound="1"
        eType="#//DataSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessing" eType="#//Preprocessing"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="CategoricalData" value="2"/>
    <eLiterals name="Integer" value="3"/>
    <eLiterals name="Float" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RSModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//Dataset"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationlayer" eType="#//PresentationLayer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluation" eType="#//Evaluation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendationSystem" lowerBound="1"
        eType="#//RecommendationSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedback" eType="#//FeedbackComponent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendedItem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outcome" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GUIElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" eType="#//UserEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserEventType">
    <eLiterals name="Click"/>
    <eLiterals name="Selection" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationHandler" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usage" upperBound="-1"
        eType="#//RecommendationUsage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webService" eType="#//WebService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//RecommendationContext"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageType" eType="#//RecommendationUsageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendedItems" upperBound="-1"
        eType="#//RecommendedItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guielements" upperBound="-1"
        eType="#//GUIElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebService" eSuperTypes="#//PresentationLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//WebInterfaceLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationContext" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProactiveSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userContext" eType="#//DataStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProactiveHandler" eSuperTypes="#//RecommendationHandler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReactiveHandler" eSuperTypes="#//RecommendationHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//UserEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RecommendationUsageType">
    <eLiterals name="Transformative"/>
    <eLiterals name="Visualization" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebApplication" eSuperTypes="#//PresentationLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//WebInterfaceLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDEIntegration" eSuperTypes="#//PresentationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSCodePlugin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handler" lowerBound="1"
        upperBound="-1" eType="#//RecommendationHandler"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraversableGraph" eSuperTypes="#//PresentationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationTechnique" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nOfRecommendations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Metric">
    <eLiterals name="Precision"/>
    <eLiterals name="Recall" value="1"/>
    <eLiterals name="F1_Measure" value="2"/>
    <eLiterals name="Catalog_Coverage" value="3"/>
    <eLiterals name="Novelty" value="4"/>
    <eLiterals name="Sale_Diversity" value="5"/>
    <eLiterals name="NDCG" value="6"/>
    <eLiterals name="Item_Coverage" value="7"/>
    <eLiterals name="EPC" value="8"/>
    <eLiterals name="GINI" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WebContainer">
    <eLiterals name="Tomcat"/>
    <eLiterals name="Jetty" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsupervisedDataset" eSuperTypes="#//Dataset"/>
  <eClassifiers xsi:type="ecore:EClass" name="Preprocessing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessingTechnique"
        upperBound="-1" eType="#//PreprocessingTechnique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeRepository" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationChannel" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BugTrackingSystem" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" eType="#//VariableRelation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//Graph"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextualContext" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARFF" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationSetting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineLearningBasedRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numEpochs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="learningRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="miniBatchSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filteringRSAlgorithm" eType="#//FilteringRSAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarityCalculator" eType="#//SimilarityFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cutoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neighborhood" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FilteringRSAlgorithm">
    <eLiterals name="Content_Based"/>
    <eLiterals name="Demographic" value="1"/>
    <eLiterals name="User_Based" value="2"/>
    <eLiterals name="Item_Based" value="3"/>
    <eLiterals name="Context_Aware" value="4"/>
    <eLiterals name="Hybrid" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimilarityFunction">
    <eLiterals name="Cosine_Similarity"/>
    <eLiterals name="Jaccard_Distance" value="1"/>
    <eLiterals name="Word_Embeddings" value="2"/>
    <eLiterals name="Levenshtein_Distance" value="3"/>
    <eLiterals name="Svd" value="4"/>
    <eLiterals name="Graph_Based" value="5"/>
    <eLiterals name="Msd" value="6"/>
    <eLiterals name="Euclidean_Distance" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMiningRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataMiningRSAlgorithm"
        eType="#//DataMiningRSAlgorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataMiningRSAlgorithm">
    <eLiterals name="Clusters"/>
    <eLiterals name="Frequent_Item_Set" value="1"/>
    <eLiterals name="Association_Rule" value="2"/>
    <eLiterals name="Event_Stream" value="3"/>
    <eLiterals name="Text_Mining" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomRecommender" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredTools" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneticAlgorithm" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fitnessFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchStrategy" eType="#//SearchStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutationOperator" eType="#//MutationOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SearchStrategy">
    <eLiterals name="Simulated_Anneling"/>
    <eLiterals name="Hill_Climbing" value="1"/>
    <eLiterals name="Gradient_Descent" value="2"/>
    <eLiterals name="Eggholder_Function" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MutationOperation">
    <eLiterals name="Fit_Bit"/>
    <eLiterals name="Crossover" value="1"/>
    <eLiterals name="Shrink_Mutation" value="2"/>
    <eLiterals name="Repace_Mutation" value="3"/>
    <eLiterals name="Partial_Hyper_Mutation" value="4"/>
    <eLiterals name="Duplication" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserStudyAnalysis">
    <eLiterals name="Qualitative"/>
    <eLiterals name="Quantitative" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossValidation" eSuperTypes="#//AutomatedValidation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfFold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groundTruthExtraction"
        eType="#//GroundTruthExtraction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomatedValidation" eSuperTypes="#//ValidationTechnique">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//ValidationLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroundTruthExtraction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeGT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splittingRules" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetVariable" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyManager" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackLibType">
    <eLiterals name="Lightfm"/>
    <eLiterals name="Lightgbm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SolverType">
    <eLiterals name="Adam"/>
    <eLiterals name="Lbfgs" value="1"/>
    <eLiterals name="Sgd" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KernelType">
    <eLiterals name="Precomputed"/>
    <eLiterals name="Linear" value="1"/>
    <eLiterals name="Poly" value="2"/>
    <eLiterals name="Rbf" value="3"/>
    <eLiterals name="Sigmoid" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivationType">
    <eLiterals name="Relu"/>
    <eLiterals name="Sigmoid" value="1"/>
    <eLiterals name="Tanh" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextValidation" eSuperTypes="#//ValidationTechnique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testContext" eType="#//RecommendationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RawFormat">
    <eLiterals name="CSV"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeepNN" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numHiddenLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConvolutionalNN" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecurrentNN" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bayesian" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Svm" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kernel" eType="#//KernelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionTree" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeedFowardNN" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="solver" eType="#//SolverType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationFunction" eType="#//ActivationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressedFeedback" eType="#//Feedback"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//RecommendationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveFeedback" eSuperTypes="#//Feedback">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfInsertion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommender" eType="#//RecommendationSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitFeedback" eSuperTypes="#//Feedback"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rating" eSuperTypes="#//ExplicitFeedback">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RatingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RatingType">
    <eLiterals name="Positive"/>
    <eLiterals name="Negative" value="1"/>
    <eLiterals name="Numerical" value="2"/>
    <eLiterals name="Ordinal" value="3"/>
    <eLiterals name="Unary" value="4"/>
  </eClassifiers>
</ecore:EPackage>
