<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RecommenderSpecification" nsURI="http://www.example.org/RecommenderSpecification"
    nsPrefix="RecommenderSpecification">
  <eClassifiers xsi:type="ecore:EClass" name="RecommenderSpecification">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RecommenderSpecification"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" eType="#//AlgorithmLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="AlgorithmComponent"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DatasetComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasettype" lowerBound="1"
        upperBound="-1" eType="#//DatasetType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessing" upperBound="-1"
        eType="#//PreprocessingComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datasetManipulationLibrary"
        upperBound="-1" eType="#//DatasetLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DataStructure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Matrix"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="DatasetType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superviseddataset" lowerBound="1"
        upperBound="-1" eType="#//SupervisedDataset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisedDataset">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="SupervisedDataset"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="EvaluationComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//EvaluationLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomSpltting">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RandomSpltting"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserStudy">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="UserStudy"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="PresentationComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawoutcomes" eType="#//RawOutcomes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RawOutcomes">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="RawOutcomes"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackComponent">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FeedbackComponent"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedbacktype" upperBound="-1"
        eType="#//FeedBackType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//FeedbackLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedBackType">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="FeedBackType"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hybrid" eType="#//Hybrid"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hybrid">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="Hybrid"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridBased">
    <eAnnotations source="FM2UMM">
      <details key="feature" value="HybridBased"/>
    </eAnnotations>
    <eAnnotations source="FM2UMM">
      <details key="leaf" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PreprocessingComponent">
    <eLiterals name="Normalization"/>
    <eLiterals name="DuplicatesRemoval" value="1"/>
    <eLiterals name="MissingDataManipulation" value="2"/>
    <eLiterals name="FeatureScaling" value="3"/>
    <eLiterals name="Vectorization" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollaborativeFiltering">
    <eLiterals name="ItemBased"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserStudyType">
    <eLiterals name="ControlledExperiment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackLibrary">
    <eLiterals name="LightFM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatasetLibrary">
    <eLiterals name="Pandas"/>
    <eLiterals name="Numpy" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgorithmLibrary">
    <eLiterals name="Surprise"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EvaluationLibrary">
    <eLiterals name="Surprise"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WebLibrary">
    <eLiterals name="Flask"/>
  </eClassifiers>
</ecore:EPackage>
