/*
 * generated by Xtext 2.32.0
 */
package shapes.myconstructor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ShapesStandaloneSetup extends ShapesStandaloneSetupGenerated {

	public static void doSetup() {
		new ShapesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
