/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import diro.geodes.ide.contentassist.antlr.internal.InternalVcsFeaturesParser;
import diro.geodes.services.VcsFeaturesGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class VcsFeaturesParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(VcsFeaturesGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, VcsFeaturesGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getMergeStrategyAccess().getAlternatives(), "rule__MergeStrategy__Alternatives");
			builder.put(grammarAccess.getLowCommandsAccess().getAlternatives(), "rule__LowCommands__Alternatives");
			builder.put(grammarAccess.getLabelTypeAccess().getAlternatives(), "rule__LabelType__Alternatives");
			builder.put(grammarAccess.getVersionUnitTypeAccess().getAlternatives(), "rule__VersionUnitType__Alternatives");
			builder.put(grammarAccess.getCollaborationStyleTypeAccess().getAlternatives(), "rule__CollaborationStyleType__Alternatives");
			builder.put(grammarAccess.getDatabaseTypeAccess().getAlternatives(), "rule__DatabaseType__Alternatives");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup(), "rule__VCSFeatures__Group__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_4(), "rule__VCSFeatures__Group_4__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_4_2(), "rule__VCSFeatures__Group_4_2__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_6(), "rule__VCSFeatures__Group_6__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_6_2(), "rule__VCSFeatures__Group_6_2__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_8(), "rule__VCSFeatures__Group_8__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_8_2(), "rule__VCSFeatures__Group_8_2__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_10(), "rule__VCSFeatures__Group_10__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_10_3(), "rule__VCSFeatures__Group_10_3__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getGroup_12(), "rule__VCSFeatures__Group_12__0");
			builder.put(grammarAccess.getCommandsAccess().getGroup(), "rule__Commands__Group__0");
			builder.put(grammarAccess.getCommandsAccess().getGroup_1(), "rule__Commands__Group_1__0");
			builder.put(grammarAccess.getCommandsAccess().getGroup_2(), "rule__Commands__Group_2__0");
			builder.put(grammarAccess.getCommandsAccess().getGroup_3(), "rule__Commands__Group_3__0");
			builder.put(grammarAccess.getHistoryAccess().getGroup(), "rule__History__Group__0");
			builder.put(grammarAccess.getHistoryAccess().getGroup_1(), "rule__History__Group_1__0");
			builder.put(grammarAccess.getHistoryAccess().getGroup_2(), "rule__History__Group_2__0");
			builder.put(grammarAccess.getHistoryAccess().getGroup_3(), "rule__History__Group_3__0");
			builder.put(grammarAccess.getVersionUnitAccess().getGroup(), "rule__VersionUnit__Group__0");
			builder.put(grammarAccess.getVersionUnitAccess().getGroup_3(), "rule__VersionUnit__Group_3__0");
			builder.put(grammarAccess.getCollaborationStyleAccess().getGroup(), "rule__CollaborationStyle__Group__0");
			builder.put(grammarAccess.getDatabaseAccess().getGroup(), "rule__Database__Group__0");
			builder.put(grammarAccess.getHighLevelCommandAccess().getGroup(), "rule__HighLevelCommand__Group__0");
			builder.put(grammarAccess.getHighLevelCommandAccess().getGroup_5(), "rule__HighLevelCommand__Group_5__0");
			builder.put(grammarAccess.getHighLevelCommandAccess().getGroup_5_2(), "rule__HighLevelCommand__Group_5_2__0");
			builder.put(grammarAccess.getLowLevelCommandAccess().getGroup(), "rule__LowLevelCommand__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getVCSFeaturesAccess().getNameAssignment_2(), "rule__VCSFeatures__NameAssignment_2");
			builder.put(grammarAccess.getVCSFeaturesAccess().getCommandsAssignment_4_1(), "rule__VCSFeatures__CommandsAssignment_4_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getCommandsAssignment_4_2_1(), "rule__VCSFeatures__CommandsAssignment_4_2_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getHistoryAssignment_6_1(), "rule__VCSFeatures__HistoryAssignment_6_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getHistoryAssignment_6_2_1(), "rule__VCSFeatures__HistoryAssignment_6_2_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getVersionunitAssignment_8_1(), "rule__VCSFeatures__VersionunitAssignment_8_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getVersionunitAssignment_8_2_1(), "rule__VCSFeatures__VersionunitAssignment_8_2_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getCollaborationstyleAssignment_10_2(), "rule__VCSFeatures__CollaborationstyleAssignment_10_2");
			builder.put(grammarAccess.getVCSFeaturesAccess().getCollaborationstyleAssignment_10_3_1(), "rule__VCSFeatures__CollaborationstyleAssignment_10_3_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getDatabaseAssignment_12_1(), "rule__VCSFeatures__DatabaseAssignment_12_1");
			builder.put(grammarAccess.getVCSFeaturesAccess().getDatabaseAssignment_12_2(), "rule__VCSFeatures__DatabaseAssignment_12_2");
			builder.put(grammarAccess.getCommandsAccess().getMergeStrategyAssignment_1_2(), "rule__Commands__MergeStrategyAssignment_1_2");
			builder.put(grammarAccess.getCommandsAccess().getLowlevelcommandAssignment_2_3(), "rule__Commands__LowlevelcommandAssignment_2_3");
			builder.put(grammarAccess.getCommandsAccess().getLowlevelcommandAssignment_2_4(), "rule__Commands__LowlevelcommandAssignment_2_4");
			builder.put(grammarAccess.getCommandsAccess().getHighlevelcommandAssignment_3_3(), "rule__Commands__HighlevelcommandAssignment_3_3");
			builder.put(grammarAccess.getCommandsAccess().getHighlevelcommandAssignment_3_4(), "rule__Commands__HighlevelcommandAssignment_3_4");
			builder.put(grammarAccess.getHistoryAccess().getLabelTypeAssignment_1_2(), "rule__History__LabelTypeAssignment_1_2");
			builder.put(grammarAccess.getHistoryAccess().getCommitHistoryRangeAssignment_2_3(), "rule__History__CommitHistoryRangeAssignment_2_3");
			builder.put(grammarAccess.getHistoryAccess().getNumberOfBranchesAssignment_3_4(), "rule__History__NumberOfBranchesAssignment_3_4");
			builder.put(grammarAccess.getVersionUnitAccess().getGranularityAssignment_3_0(), "rule__VersionUnit__GranularityAssignment_3_0");
			builder.put(grammarAccess.getVersionUnitAccess().getGranularityAssignment_3_1(), "rule__VersionUnit__GranularityAssignment_3_1");
			builder.put(grammarAccess.getCollaborationStyleAccess().getCollabStyleAssignment_2(), "rule__CollaborationStyle__CollabStyleAssignment_2");
			builder.put(grammarAccess.getDatabaseAccess().getNameAssignment_2(), "rule__Database__NameAssignment_2");
			builder.put(grammarAccess.getDatabaseAccess().getDatabaseTypeAssignment_3(), "rule__Database__DatabaseTypeAssignment_3");
			builder.put(grammarAccess.getDatabaseAccess().getConnectionStringAssignment_5(), "rule__Database__ConnectionStringAssignment_5");
			builder.put(grammarAccess.getHighLevelCommandAccess().getNameAssignment_4(), "rule__HighLevelCommand__NameAssignment_4");
			builder.put(grammarAccess.getHighLevelCommandAccess().getLowlevelcommandAssignment_5_1(), "rule__HighLevelCommand__LowlevelcommandAssignment_5_1");
			builder.put(grammarAccess.getHighLevelCommandAccess().getLowlevelcommandAssignment_5_2_1(), "rule__HighLevelCommand__LowlevelcommandAssignment_5_2_1");
			builder.put(grammarAccess.getLowLevelCommandAccess().getCommandAssignment_3(), "rule__LowLevelCommand__CommandAssignment_3");
			builder.put(grammarAccess.getLowLevelCommandAccess().getNameAssignment_5(), "rule__LowLevelCommand__NameAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private VcsFeaturesGrammarAccess grammarAccess;

	@Override
	protected InternalVcsFeaturesParser createParser() {
		InternalVcsFeaturesParser result = new InternalVcsFeaturesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public VcsFeaturesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VcsFeaturesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
